#!/usr/bin/env python
# -*- coding: utf-8 -*-

import os
import codecs
import json
from bottle import request, run, get, post

# app config
app_config_path = '/etc/bsp_server.json'
password = None
if not os.path.exists(app_config_path):
    import uuid
    password = str(uuid.uuid4())[-10:-1]
    config = {
        "password" : password
    }
    with codecs.open(app_config_path, 'w', 'utf-8') as json_file:
        json_file.write(json.dumps(config, sort_keys=True, indent=4).decode('utf-8'))
else:
    with codecs.open(app_config_path) as json_file:
        data = json.load(json_file)
        password = data.get('password',None)
    if not password:
        password = str(uuid.uuid4())[-10:-1]
        config = {
            "password" : password
        }
        with codecs.open(app_config_path, 'w', 'utf-8') as json_file:
            json_file.write(json.dumps(config, sort_keys=True, indent=4).decode('utf-8'))

print "password:",password

def check_auth():
    key = request.params.get('key',None)
    return (key == password)

@post('/ping')
def ping():
    if not check_auth():
        return 'no auth'
    return "pong"

@post('/create')
def create():
    if not check_auth():
        return 'error'

    port = request.params.get('port',None)
    password = request.params.get('password',None)
    bandwith = request.params.get('bandwith',None)
    if not port or not password or not bandwith:
        return 'error'
    try:
        port = int(port)
        bandwith = int(bandwith)
    except Exception as e:
        return 'error'

    if bandwith < 0 or bandwith > 200 * 1000:
        return 'error'

    cmd = 'bsp -p %d -P %s -s %d -a -A -j'%(port,password,bandwith)
    if os.system(cmd) != 0:
        return 'error'
    else:
        return 'create ok'

@post('/delete')
def delete():
    if not check_auth():
        return 'error'

    port = request.params.get('port',None)
    if not port:
        return 'error'
    try:
        port = int(port)
    except Exception as e:
        return 'error'

    cmd = 'bsp -p %d -d -D -R'%(port)
    if os.system(cmd) != 0:
        return 'error'
    else:
        return 'delete ok'

@post('/query')
def query():
    if not check_auth():
        return 'error'

    port = request.params.get('port',None)
    if not port:
        return 'error'
    try:
        port = int(port)
    except Exception as e:
        return 'error'

    cmd = 'bsp -p %d -c'%(port)
    output = os.popen(cmd)
    c = output.read()
    if c == '':
        return 'error'
    else:
        return c
        
@post('/ports')
def ports(self):
    if not check_auth():
        return 'error'

    with codecs.open('/etc/shadowsocks.json') as json_file:
        data = json.load(json_file)
        port_password = data.get('port_password',{})
        return port_password.keys()


run(host='0.0.0.0', port=8081,reloader=True)
